language: objective-c
script:
  - bundle exec rake spec

notifications:
  slack:
    - secure: "Q4dejaQI7juTs0D7NckK7O40v/GT0WyZp8ezPYq8NYIvFYuNSGsHyuSaFZsHGIpyDquWRkmY++7MgUnGTczNsmu0eNu92XSWBedgcw9llx4KHh9ICBNM+6LTWpWV7QhH5LAp2PGvtPmQdobJ5ixp+oGqQIicHETRfrIfmUARZw6E89evEipdbBzdFp8zbWEcNirJ/L2ODqqb7+3FUG4bZhT7DqcajD/MVjHzw+URMVVOCb/PWsXLrVysJ+v97a5MYjzt1OHuQsnEzmCRUqzgNBnW28ddNgs07cD6olsWqBkXpEPLNKqSkqosXrIL/IS4ebucbL2DCkSNwKcFpzIucaTYI1X2/cNlp1BW2G9z2cm+ZwgUnoBHo/2piar0er4fIN+mpVgggzVawGDEck4NlPF7oZpmW6rK/MsMGAnUJdqZ2wKD8Ja87DJbJzVR5Fp3QdfSCAyd/WMtelqCC4x13Vw+S/swuvzCkR9QjYZGlQ7vlwXEb2fQLHJsqr/quYgWx0DKMUGuzgY/nLV2+HRwy0zNUi7ansFNPh/OphqBBUMaDuwU1DUJTPR9Ne4gqeXDZB9jIUJ3SOoCgLADZaN3YmFLjIhGZUuISjGmCN8xALL4He58TEDICiuZxyY0NhFmhTmfy7GrBySXb4sALX5iGD7Bcv0EEp9wbUzlVV1cx2U="
